apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: akshayap2901/order-service:1
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 10
